# Generated by Django 4.0.2 on 2023-03-24 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_followerscount_follower_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followerscount',
            name='follower',
            field=models.CharField(max_length=200),
        ),
    ]
